# Generated by Django 5.2.3 on 2025-06-30 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_class', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('co2e_impact', models.CharField(max_length=100)),
                ('impact_value', models.FloatField()),
                ('instrument_type', models.CharField(max_length=100)),
                ('keywords', models.JSONField(default=list)),
                ('required_input_type', models.CharField(default='budget', max_length=50)),
                ('default_unit_cost', models.FloatField(blank=True, null=True)),
                ('uses_displacement', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('displacement_ratio', models.FloatField(default=1.0)),
                ('efficiency_score', models.FloatField(default=0.5)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('target_year', models.IntegerField()),
                ('baseline_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('node_id', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=250)),
                ('impact_value', models.FloatField()),
                ('alignment', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative'), ('U', 'Neutral')], max_length=1)),
                ('node_size', models.FloatField(default=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('efficiency', models.FloatField(default=0.5)),
                ('beneficiary', models.CharField(blank=True, max_length=100)),
                ('responsible_dept', models.CharField(blank=True, max_length=100)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_graph.activity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_graph.country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_graph.intent')),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'ordering': ['-created_at'],
            },
        ),
    ]
