# Generated by Django 5.2.3 on 2025-06-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_node', models.CharField(max_length=200, unique=True)),
                ('policy_title', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('graph_intent', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
                ('co2_impact', models.FloatField()),
                ('alignment', models.CharField(max_length=50)),
                ('instrument', models.CharField(max_length=100)),
                ('start_end', models.CharField(max_length=100)),
                ('beneficiary', models.CharField(max_length=200)),
                ('influencer', models.CharField(max_length=200)),
                ('efficiency', models.FloatField()),
                ('node_size', models.FloatField()),
                ('node_color', models.CharField(max_length=30)),
                ('original_text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='policy',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='country',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Intent',
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
