# Generated by Django 5.2.3 on 2025-06-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_graph', '0002_policynode_remove_policy_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policynode',
            name='policy_node',
            field=models.CharField(max_length=200),
        ),
    ]
