# dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('ghg/', views.ghg_insights, name='ghg_insights'),
    path('ghg-trend/', views.ghg_trend_view, name='ghg_trend'),
    path('co2-emission/', views.co2_emission_view, name='co2_emission'),
    path('co2-bio/', views.co2_bio_view, name='co2_bio'),
    path('total-co2/', views.total_co2_view, name='total_co2'),
    path('ch4/', views.ch4_emissions_view, name='ch4_emissions'),
    path('n2o/', views.n2o_emissions_view, name='n2o_emissions'),
    path('intro/', views.ghg_intro_view, name='ghg_intro'),
    path('sector-summary/', views.sector_summary_view, name='sector_summary'),
    path('sector/<str:gas>/', views.sector_gas_trend_view, name='sector_gas_trend'),
    path('sector-guide/', views.sector_guide_view, name='sector_guide'),
    path("country-comparison/trends/", views.emission_trend_view, name="emission_trends"),
    path('emission-trend/', views.emission_trend_view, name='emission_trend'),
    path('sector-comparison/', views.sector_comparison_view, name='sector_comparison'),
    path('sector-radar/', views.sector_radar_view, name='sector_radar'),
    path('sector-stacked/', views.sector_stacked_view, name='sector_stacked'),
    path("intelligence/", views.emission_intelligence_view, name="emission_intelligence"),
    # Deep Insights (Module 4)
    path("deep-insights/", views.deep_intro_view, name="deep_intro"),
    path("deep-insights/sector/", views.deep_sector_view, name="deep_sector"),
    path("deep-insights/growth/", views.deep_growth_view, name="deep_growth"),
    path("deep-insights/country-benchmark/", views.deep_country_benchmark_view, name="deep_country_benchmark"),
    path("deep-insights/sector-benchmark/", views.deep_sector_benchmark_view, name="deep_sector_benchmark"),
    path("deep-insights/percapita-gdp/", views.deep_percapita_gdp_view, name="deep_percapita_gdp"),
    path("global-temp/", views.global_temp_anomaly_view, name="global_temp_anomaly"),
    path("global-zonal/", views.global_zonal_summary_view, name="global_zonal_summary"),
    path("warming-rate/", views.warming_rate_view, name="warming_rate"),
    path("equator-poles/", views.equator_vs_poles_view, name="equator_poles"),
    path("sea-level/", views.sea_level_view, name="sea_level"),
    path("global-gas/<str:gas>/", views.gas_concentration_view, name="global_gas_concentration"),
    path("global-trends/", views.global_trends_home, name="global_trends_home"),
    path("electricity/intro/", views.electricity_intro_view, name="electricity_intro_view"),
    path("electricity/summary/", views.electricity_summary_view, name="electricity_summary_view"),
    path("electricity/fuel-mix/", views.electricity_fuel_mix_view, name="electricity_fuel_mix_view"),
    path("electricity/map/", views.electricity_map_view, name="electricity_map_view"),
    path("electricity/capacity-trend/", views.electricity_capacity_trend_view, name="electricity_capacity_trend_view"),
    path("electricity/avg-capacity/", views.electricity_avg_capacity_view, name="electricity_avg_capacity_view"),
    path("electricity/efficiency/", views.electricity_efficiency_view, name="electricity_efficiency_view"),
    path("electricity/fuel-mix-over-time/", views.electricity_fuel_mix_time_view, name="electricity_fuel_mix_time_view"),
    path("electricity/about/", views.electricity_about_view, name="electricity_about_view"),
    path("renewable/intro/", views.renewable_intro_view, name="renewable_intro"),
    path("renewable/trend/", views.renewable_trend_view, name="renewable_trend"),
    path("renewable/source-breakdown/", views.renewable_source_breakdown_view, name="renewable_source_breakdown"),
    path("renewable/top-countries/", views.renewable_top_countries_view, name="renewable_top_countries"),
    path("renewable/fastest-growth/", views.renewable_fastest_growth_view, name="renewable_fastest_growth"),
    path("renewable/electricity-mix/", views.renewable_electricity_mix_view, name="renewable_electricity_mix"),
]

