# Generated by Django 5.2.3 on 2025-06-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.CharField(blank=True, choices=[('India', 'INDIA'), ('usa', 'USA'), ('Canada', 'CANADA')], null=True),
        ),
    ]
