# Generated by Django 5.2.3 on 2025-07-22 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('revision_of', 'Revision Of'), ('amendment_of', 'Amendment Of'), ('related_to', 'Related To')], max_length=100)),
                ('similarity_score', models.FloatField()),
                ('inferred_from', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='policy_analysis.policy')),
                ('parent_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='policy_analysis.policy')),
            ],
            options={
                'unique_together': {('parent_policy', 'child_policy', 'relationship_type')},
            },
        ),
    ]
